// Seed data for AlumniStory. Used on /api/alumni for "students like you"
// matching shown on the eligibility result page and the profile page.

export const ALUMNI_SEED = [
  { initials: "F.R.", country: "CA", program: "MSc Computer Science", university: "University of Toronto", field: "CS", level: "MASTER", gpa4: 3.62, ielts: 7.0, year: 2025, scholarship: "$12,000 entrance grant", quote: "The SOP review made the difference — I got in with a safety program first." , featured: true },
  { initials: "A.H.", country: "AU", program: "Master of Business Analytics", university: "Univ. of Melbourne", field: "BUSINESS", level: "MASTER", gpa4: 3.45, ielts: 6.5, year: 2025, scholarship: null, quote: "Visa approved in 21 days — the mock interview drilled me on my GS answers.", featured: true },
  { initials: "T.K.", country: "UK", program: "MSc Data Science", university: "UCL", field: "CS", level: "MASTER", gpa4: 3.8, ielts: 7.5, year: 2025, scholarship: "£5,000 Edinburgh Global", quote: "Graduate Route visa got me my first job within 3 months." },
  { initials: "S.M.", country: "DE", program: "MSc Mechanical Engineering", university: "TU Munich", field: "ENGINEERING", level: "MASTER", gpa4: 3.2, ielts: 6.5, year: 2024, scholarship: "Tuition-free public uni", quote: "APS took 5 weeks — plan ahead. Blocked account through Fintiba was smooth." },
  { initials: "N.I.", country: "IE", program: "MSc Pharmaceutical Sciences", university: "Trinity College Dublin", field: "SCIENCE", level: "MASTER", gpa4: 3.55, ielts: 6.5, year: 2024, scholarship: "€10,000 Global Excellence", quote: "Stay Back visa let me land a research role without leaving Dublin." },
  { initials: "R.A.", country: "US", program: "MS in Information Systems", university: "Stanford", field: "CS", level: "MASTER", gpa4: 3.9, ielts: 7.5, year: 2024, scholarship: "Partial merit aid", quote: "I was rejected once for 214(b). Second interview — same embassy, better answers — approved." },
  { initials: "I.K.", country: "CA", program: "MEng Electrical Engineering", university: "UBC", field: "ENGINEERING", level: "MASTER", gpa4: 3.3, ielts: 6.5, year: 2024, scholarship: null, quote: "SDS route — GIC + first-year tuition upfront — cleared in 19 days." },
  { initials: "H.S.", country: "AU", program: "Bachelor of IT", university: "Univ. of Sydney", field: "CS", level: "BACHELOR", gpa4: 3.4, ielts: 6.5, year: 2024, scholarship: "Sydney Scholars AUD 10k", quote: "I was borderline; the counselor picked a program-fit I wouldn't have found." },
  { initials: "M.A.", country: "UK", program: "LLM International Law", university: "Queen Mary", field: "LAW", level: "MASTER", gpa4: 3.6, ielts: 7.0, year: 2024, scholarship: null, quote: "CAS issued in 3 days after submitting IELTS. TB test at IOM is a must." },
  { initials: "P.D.", country: "DE", program: "MSc Embedded Systems", university: "RWTH Aachen", field: "ENGINEERING", level: "MASTER", gpa4: 3.1, ielts: 6.0, year: 2023, scholarship: "€300/mo Deutschland Stipendium", quote: "APS is a grind but worth it — public uni means near-zero debt." },
  { initials: "J.B.", country: "CA", program: "Postgrad Certificate Data Analytics", university: "Lakehead University", field: "CS", level: "DIPLOMA", gpa4: 2.9, ielts: 6.0, year: 2024, scholarship: null, quote: "Diploma pathway was the right move for my GPA — now doing PGWP work." },
  { initials: "A.N.", country: "US", program: "MS Computer Science", university: "MIT", field: "CS", level: "MASTER", gpa4: 3.95, ielts: 8.0, year: 2023, scholarship: "Full MIT fellowship", quote: "Reaches pay off — but have 2 match + 2 safety programs too.", featured: true },
  { initials: "Z.H.", country: "IE", program: "Higher Diploma Computing", university: "NCI Dublin", field: "CS", level: "DIPLOMA", gpa4: 2.8, ielts: 6.0, year: 2024, scholarship: null, quote: "ROI was crazy — Stay Back lets me earn while paying off my loan." },
  { initials: "K.R.", country: "AU", program: "MSc Nursing", university: "Monash", field: "HEALTH", level: "MASTER", gpa4: 3.5, ielts: 7.0, year: 2024, scholarship: "AUD 15k merit", quote: "Genuine Student answers need specifics — vague will fail." },
  { initials: "O.S.", country: "UK", program: "MBA", university: "Warwick Business School", field: "BUSINESS", level: "MASTER", gpa4: 3.7, ielts: 7.5, year: 2024, scholarship: "Chevening full", quote: "Chevening application was a 6-month process — the essays are everything." },
  { initials: "L.M.", country: "CA", program: "BSc Biomedical Sciences", university: "Western University", field: "SCIENCE", level: "BACHELOR", gpa4: 3.7, ielts: 7.0, year: 2024, scholarship: "President's Entrance CAD 20k", quote: "Applied with an 85% average — the entrance scholarship was automatic." },
  { initials: "V.T.", country: "DE", program: "Master of Automotive Engineering", university: "TU Munich", field: "ENGINEERING", level: "MASTER", gpa4: 3.4, ielts: 6.5, year: 2023, scholarship: null, quote: "German A2 helped me get a werkstudent role — living costs halved." },
  { initials: "C.B.", country: "US", program: "MS Electrical Engineering", university: "Texas A&M", field: "ENGINEERING", level: "MASTER", gpa4: 3.5, ielts: 7.0, year: 2024, scholarship: "50% tuition waiver", quote: "Out-of-state waivers exist — ask specifically, don't assume." },
  { initials: "D.I.", country: "IE", program: "MSc Finance", university: "UCD Smurfit", field: "BUSINESS", level: "MASTER", gpa4: 3.6, ielts: 7.0, year: 2024, scholarship: "€5,000 International", quote: "Tier 5 banking sector loves the CFA + Irish Master's combo." },
  { initials: "E.Y.", country: "UK", program: "MSc Development Economics", university: "SOAS", field: "BUSINESS", level: "MASTER", gpa4: 3.5, ielts: 7.0, year: 2023, scholarship: "Commonwealth shared", quote: "SOAS essay prompt rewarded honesty about fieldwork in rural Bangladesh." },
];
