export type VisaRequirement = {
  country: string;
  processingDays: string;
  fee: string;
  documents: string[];
  rejections: string[];
  embassyUrl: string;
  appointmentUrl?: string;
  notes: string;
};

export const VISA_REQUIREMENTS: Record<string, VisaRequirement> = {
  AU: {
    country: "Australia",
    processingDays: "4-8 weeks (sub-class 500)",
    fee: "AUD 1,600 (~USD 1,050)",
    documents: [
      "Passport (valid 6+ months)",
      "Confirmation of Enrolment (CoE)",
      "OSHC (overseas student health cover)",
      "Academic transcripts & certificates",
      "IELTS / PTE certificate",
      "Statement of Purpose (Genuine Student requirement since 2024)",
      "Bank statements showing 12 months living costs + first-year tuition",
      "Health check & police clearance if requested",
    ],
    rejections: [
      "Weak Genuine Student statement",
      "Insufficient or unexplained finances",
      "Course-choice inconsistent with academic/work background",
      "Past visa refusals not disclosed",
    ],
    embassyUrl: "https://immi.homeaffairs.gov.au",
    appointmentUrl: "https://online.immi.gov.au",
    notes:
      "Since 2024 Australia uses the Genuine Student (GS) requirement instead of GTE — expect detailed questions on study plan and ties to Bangladesh.",
  },
  CA: {
    country: "Canada",
    processingDays: "8-12 weeks (SDS can be faster: 4-6 weeks)",
    fee: "CAD 150 study permit + CAD 85 biometrics",
    documents: [
      "Valid passport",
      "Letter of Acceptance from DLI",
      "Proof of funds (SDS: GIC of CAD 20,635 + first-year tuition)",
      "IELTS 6.0+ (SDS requires 6.0 in each band)",
      "Medical exam (panel physician)",
      "Statement of Purpose",
      "Academic transcripts",
      "Police clearance certificate",
    ],
    rejections: [
      "Weak ties to home country",
      "Insufficient or dubious source of funds",
      "GIC / tuition payment mismatch",
      "Incomplete SOP (purpose of study unclear)",
    ],
    embassyUrl: "https://www.canada.ca/en/immigration-refugees-citizenship",
    appointmentUrl: "https://visa.vfsglobal.com/bgd/en/can",
    notes:
      "Student Direct Stream (SDS) is the fastest route — requires IELTS 6.0 each band, GIC, and upfront first-year tuition.",
  },
  US: {
    country: "United States",
    processingDays: "2-8 weeks (varies by embassy slot availability)",
    fee: "USD 185 visa fee + USD 350 SEVIS I-901",
    documents: [
      "Passport",
      "I-20 from SEVP-approved school",
      "DS-160 confirmation",
      "SEVIS fee receipt",
      "Interview appointment letter",
      "Proof of funds (1 year tuition + living)",
      "Academic transcripts",
      "Test scores (TOEFL/IELTS/GRE/GMAT as required)",
    ],
    rejections: [
      "214(b) — failure to prove intent to return",
      "Weak financial documentation",
      "Inconsistent answers at interview",
      "No clear career plan linking US degree to home country",
    ],
    embassyUrl: "https://bd.usembassy.gov/visas/",
    appointmentUrl: "https://ais.usvisa-info.com",
    notes:
      "The interview is the decisive step. Prepare for questions on why this university, why this program, and what you will do after graduation.",
  },
  UK: {
    country: "United Kingdom",
    processingDays: "3 weeks from biometrics (Priority: 5 working days)",
    fee: "£490 + £776/year IHS (health surcharge)",
    documents: [
      "Passport",
      "CAS (Confirmation of Acceptance for Studies)",
      "Financial evidence (28 days held, tuition + £1,334/mo London or £1,023/mo elsewhere × 9 months)",
      "IELTS / Secure English Language Test (SELT) if required",
      "ATAS certificate (for some STEM subjects)",
      "Tuberculosis test certificate (Bangladesh: mandatory)",
      "Academic transcripts + CAS-mentioned documents",
    ],
    rejections: [
      "Credibility interview failure",
      "Finances not held long enough (28-day rule)",
      "Incorrect or missing CAS details",
      "Academic progression concerns",
    ],
    embassyUrl: "https://www.gov.uk/student-visa",
    appointmentUrl: "https://visa.vfsglobal.com/bgd/en/gbr",
    notes:
      "Bangladesh-applied visas require the TB test from an IOM-approved clinic. The Graduate Route gives 2 years post-study work after completion.",
  },
  DE: {
    country: "Germany",
    processingDays: "6-12 weeks (book slots 2-3 months in advance)",
    fee: "€75 (~USD 80)",
    documents: [
      "Passport",
      "University admission letter",
      "Blocked account of €11,904/year (Fintiba, Expatrio, Coracle, Deutsche Bank)",
      "Health insurance (Mawista, TK, etc.)",
      "Academic transcripts (APS-verified for Bangladeshi students)",
      "German language (A1/A2) or English proficiency depending on program",
      "Motivation letter",
      "CV",
    ],
    rejections: [
      "Missing APS certificate (mandatory for Bangladesh/India/China)",
      "Blocked account amount short of current threshold",
      "Weak motivation letter",
      "Academic gaps without explanation",
    ],
    embassyUrl: "https://dhaka.diplo.de",
    appointmentUrl: "https://service2.diplo.de",
    notes:
      "APS (Akademische Prüfstelle) certification is mandatory before visa application for Bangladeshi students. Plan 4-6 weeks for APS alone.",
  },
  IE: {
    country: "Ireland",
    processingDays: "4-8 weeks (D-Type long-stay study visa)",
    fee: "€60 single entry / €100 multiple",
    documents: [
      "Passport",
      "Letter of Acceptance",
      "Evidence of tuition paid",
      "Proof of €10,000 maintenance funds",
      "Private medical insurance",
      "English proficiency (IELTS 6.0+ typical)",
      "Academic documents",
      "Gap year explanation letter (if applicable)",
    ],
    rejections: [
      "Insufficient maintenance funds",
      "Course choice not aligned with prior studies",
      "Weak ties to Bangladesh",
    ],
    embassyUrl: "https://www.irishimmigration.ie",
    appointmentUrl: "https://www.visaireland.com",
    notes:
      "Ireland's Third Level Graduate scheme (Stay Back) allows 1-2 years of post-study work depending on NFQ level.",
  },
  NZ: {
    country: "New Zealand",
    processingDays: "4-8 weeks (Fee-Paying Student Visa)",
    fee: "NZD 375 online + NZD 210 IHL",
    documents: [
      "Passport",
      "Offer of place from NZ-approved institution",
      "Evidence of funds (NZD 20,000/year for living)",
      "Medical + chest X-ray (Bangladeshi applicants)",
      "IELTS / PTE (6.0+ overall typical)",
      "Police clearance",
      "Statement of Purpose",
      "Tuition receipt or bank guarantee",
    ],
    rejections: [
      "Genuine Temporary Entrant (GTE) failure",
      "Insufficient funds or unclear source",
      "Weak ties to Bangladesh",
      "Previous visa refusals not disclosed",
    ],
    embassyUrl: "https://www.immigration.govt.nz",
    appointmentUrl: "https://visa.vfsglobal.com/bgd/en/nzl",
    notes:
      "Post-study work visa is up to 3 years depending on qualification level. Assistant/Pathway colleges require extra scrutiny.",
  },
  FR: {
    country: "France",
    processingDays: "3-6 weeks (VLS-TS long-stay student visa)",
    fee: "€99 + €50 Campus France fee",
    documents: [
      "Passport",
      "Campus France clearance (mandatory for Bangladeshi students)",
      "Admission letter from accredited institution",
      "Proof of funds (€7,380/year minimum)",
      "Accommodation proof",
      "Health insurance",
      "Motivation letter",
      "Academic transcripts",
    ],
    rejections: [
      "Weak Campus France interview",
      "Unconvincing study plan",
      "Finances short of minimum threshold",
    ],
    embassyUrl: "https://france-visas.gouv.fr",
    appointmentUrl: "https://www.vfsglobal.com/france/bangladesh",
    notes:
      "All Bangladeshi students must go through Campus France before the visa interview. Budget 6-8 weeks for Campus France + visa combined.",
  },
  FI: {
    country: "Finland",
    processingDays: "1-3 months",
    fee: "€450 (first permit, paper) / €350 (electronic)",
    documents: [
      "Passport",
      "Admission letter",
      "Proof of €6,720/year funds",
      "Health insurance",
      "Apostille-attested academic documents",
      "Motivation letter",
      "Accommodation proof (if available)",
    ],
    rejections: [
      "Insufficient maintenance funds",
      "Unclear study plan / career linkage",
      "Incomplete document attestation",
    ],
    embassyUrl: "https://migri.fi",
    appointmentUrl: "https://enterfinland.fi",
    notes:
      "Biometrics are collected at VFS New Delhi — plan the trip in advance. Apply online via Enter Finland, then visit the visa application centre.",
  },
  NL: {
    country: "Netherlands",
    processingDays: "2-4 weeks (MVV via institution sponsorship)",
    fee: "€228 application fee",
    documents: [
      "Passport",
      "Admission letter from IND-recognised sponsor",
      "Proof of €13,440/year funds (transferred to institution or blocked)",
      "Health insurance",
      "TB test (Bangladeshi students)",
      "Academic transcripts",
      "Declaration of Truth",
    ],
    rejections: [
      "Fake documents or finances",
      "Study gap without explanation",
      "Previous Schengen refusals",
    ],
    embassyUrl: "https://ind.nl",
    appointmentUrl: "https://www.vfsglobal.com/netherlands/bangladesh",
    notes:
      "Your university files the MVV application on your behalf — start 3 months before intake. Post-study Orientation Year visa gives 12 months of full work rights.",
  },
  ES: {
    country: "Spain",
    processingDays: "1-3 months",
    fee: "€80 + NIE fees",
    documents: [
      "Passport",
      "Admission letter from Spanish institution",
      "Proof of funds (IPREM × 100% = €600/month)",
      "Health insurance (no co-pay)",
      "Police clearance (apostilled)",
      "Medical certificate",
      "Academic documents (apostilled)",
    ],
    rejections: [
      "Insufficient funds / wrong bank format",
      "Weak motivation letter",
      "Incomplete apostille of academic docs",
    ],
    embassyUrl: "https://www.exteriores.gob.es",
    appointmentUrl: "https://www.blsspainvisa.com/bangladesh",
    notes:
      "Apostille of all academic and legal documents is mandatory. Post-study 1-year job-search extension available.",
  },
  IT: {
    country: "Italy",
    processingDays: "1-3 months",
    fee: "€50 Type D student visa fee",
    documents: [
      "Passport",
      "Pre-enrolment via Universitaly (mandatory)",
      "Admission letter",
      "Proof of funds (€6,079.45/year)",
      "Accommodation proof",
      "Health insurance",
      "DoV (Declaration of Value) + academic legalisations",
    ],
    rejections: [
      "Missing or delayed Universitaly pre-enrolment",
      "Incomplete DoV",
      "Weak motivation letter",
    ],
    embassyUrl: "https://vistoperitalia.esteri.it",
    appointmentUrl: "https://www.vfsglobal.com/italy/bangladesh",
    notes:
      "Pre-enrolment on Universitaly is the gating step — start in June for September intake. Strong emphasis on DoV and CIMEA statements.",
  },
  HU: {
    country: "Hungary",
    processingDays: "4-6 weeks",
    fee: "€110 long-stay visa",
    documents: [
      "Passport",
      "Admission letter (Stipendium Hungaricum or self-funded)",
      "Proof of funds (approx. €5,000/year)",
      "Accommodation proof",
      "Health insurance",
      "Academic documents",
      "Police clearance",
    ],
    rejections: [
      "Fake or inconsistent finances",
      "Weak motivation",
      "Unclear post-study plan",
    ],
    embassyUrl: "https://konzuliszolgalat.kormany.hu",
    appointmentUrl: "https://enterhungary.gov.hu",
    notes:
      "Stipendium Hungaricum scholarship covers tuition + stipend — apply in January for the next academic year.",
  },
  CY: {
    country: "Cyprus",
    processingDays: "2-4 weeks (student entry permit)",
    fee: "€200 (permit fee)",
    documents: [
      "Passport",
      "Admission letter",
      "Tuition fee payment receipt",
      "Medical tests (HIV, Hepatitis B/C, Syphilis, TB)",
      "Proof of funds (€8,000-€10,000)",
      "Bank guarantee",
      "Accommodation proof",
    ],
    rejections: [
      "Medical test failure",
      "Weak bank guarantee",
      "Unclear academic progression",
    ],
    embassyUrl: "https://www.moi.gov.cy",
    appointmentUrl: "https://www.vfsglobal.com/cyprus/bangladesh",
    notes:
      "Mandatory medical tests must be done within 7 days of arrival. The visa is normally issued as a provisional entry permit at the border.",
  },
  CH: {
    country: "Switzerland",
    processingDays: "6-12 weeks",
    fee: "CHF 80 visa + residence permit fee on arrival",
    documents: [
      "Passport",
      "Admission letter",
      "Proof of funds (CHF 21,000/year minimum)",
      "Accommodation proof",
      "Health insurance",
      "Motivation letter",
      "Academic & police documents",
    ],
    rejections: [
      "Finances below canton threshold",
      "Weak study motivation letter",
      "Incomplete cantonal forms",
    ],
    embassyUrl: "https://www.sem.admin.ch",
    appointmentUrl: "https://www.vfsglobal.com/switzerland/bangladesh",
    notes:
      "Each canton issues its own residence permit — rules differ between Zurich, Geneva, Lausanne etc. Work rights start 6 months after arrival.",
  },
  SE: {
    country: "Sweden",
    processingDays: "1-3 months",
    fee: "SEK 1,500 (~€130) student permit",
    documents: [
      "Passport",
      "Admission letter",
      "Proof of funds (SEK 11,079/month)",
      "Health insurance",
      "Tuition fee receipt",
      "Academic documents",
    ],
    rejections: [
      "Insufficient proof of funds",
      "Missing tuition fee receipt",
      "Weak academic progression",
    ],
    embassyUrl: "https://www.migrationsverket.se",
    appointmentUrl: "https://www.vfsglobal.com/sweden/bangladesh",
    notes:
      "You apply online at Migrationsverket; biometrics are taken at the visa centre in Dhaka (VFS). 12-month post-study residence permit available.",
  },
  DK: {
    country: "Denmark",
    processingDays: "4-8 weeks",
    fee: "DKK 2,075 (~€280)",
    documents: [
      "Passport",
      "Admission letter",
      "Proof of DKK 76,992 funds",
      "Health insurance",
      "Motivation letter",
      "Academic documents",
    ],
    rejections: [
      "Weak funding proof",
      "Unclear study plan",
      "Incomplete documentation",
    ],
    embassyUrl: "https://nyidanmark.dk",
    appointmentUrl: "https://www.vfsglobal.com/denmark/bangladesh",
    notes:
      "Establishment Card gives you up to 3 years post-study to find work. Biometrics at VFS Dhaka required.",
  },
  BE: {
    country: "Belgium",
    processingDays: "1-3 months",
    fee: "€195 long-stay student visa",
    documents: [
      "Passport",
      "Admission letter",
      "Proof of €12,600/year funds (official financial commitment)",
      "Health insurance",
      "Police clearance",
      "Medical certificate",
      "Academic documents (apostilled)",
    ],
    rejections: [
      "Financial commitment not in approved format",
      "Weak motivation letter",
      "Academic documents not apostilled",
    ],
    embassyUrl: "https://dofi.ibz.be",
    appointmentUrl: "https://www.vfsglobal.com/belgium/bangladesh",
    notes:
      "The financial commitment must follow Belgium's 'Annex 32' template signed by a guarantor. Plan 2-3 months minimum.",
  },
  AT: {
    country: "Austria",
    processingDays: "2-4 months",
    fee: "€150 residence permit 'Student'",
    documents: [
      "Passport",
      "Admission letter",
      "Proof of €12,526/year funds",
      "Accommodation proof",
      "Health insurance",
      "Police clearance",
      "Academic documents",
    ],
    rejections: [
      "Insufficient funds threshold",
      "Accommodation proof missing",
      "Unclear study plan",
    ],
    embassyUrl: "https://www.bmeia.gv.at",
    appointmentUrl: "https://www.vfsglobal.com/austria/bangladesh",
    notes:
      "Apply for 'Aufenthaltsbewilligung — Student'. Plan at least 3-4 months ahead of semester.",
  },
  MT: {
    country: "Malta",
    processingDays: "4-6 weeks",
    fee: "€66 visa + €230 residence",
    documents: [
      "Passport",
      "Admission letter",
      "Proof of €7,000/year funds",
      "Health insurance",
      "Accommodation proof",
      "Police clearance",
      "Academic documents",
    ],
    rejections: [
      "Weak finances",
      "Unclear study purpose",
      "Insufficient English proficiency",
    ],
    embassyUrl: "https://identitymalta.com",
    appointmentUrl: "https://www.vfsglobal.com/malta/bangladesh",
    notes:
      "English is the official medium of instruction. Post-study work options are limited — most students aim for EU mobility afterwards.",
  },
  PL: {
    country: "Poland",
    processingDays: "2-4 weeks",
    fee: "€80 Type D visa",
    documents: [
      "Passport",
      "Admission letter",
      "Proof of €701/month for 15 months",
      "Health insurance",
      "Academic documents",
      "Accommodation proof",
    ],
    rejections: [
      "Low-quality finances proof",
      "Unclear study plan",
      "Schengen refusal history",
    ],
    embassyUrl: "https://www.gov.pl",
    appointmentUrl: "https://www.vfsglobal.com/poland/bangladesh",
    notes:
      "Poland permits full-time work during summer break and 20 hours/week during semester — attractive for self-funded students.",
  },
  LT: {
    country: "Lithuania",
    processingDays: "2-4 weeks",
    fee: "€120 D visa",
    documents: [
      "Passport",
      "Admission letter",
      "Proof of €540/month funds",
      "Health insurance",
      "Accommodation proof",
      "Police clearance",
    ],
    rejections: [
      "Inadequate funds",
      "Unclear motivation",
      "Academic mismatch",
    ],
    embassyUrl: "https://migracija.lrv.lt",
    appointmentUrl: "https://www.vfsglobal.com/lithuania/bangladesh",
    notes:
      "One of the cheapest routes to an EU degree. Part-time work rights during study.",
  },
  CN: {
    country: "China",
    processingDays: "2-4 weeks (X1 / X2 student visa)",
    fee: "USD 30-140 depending on entries",
    documents: [
      "Passport",
      "JW201 or JW202 form",
      "Admission letter (original)",
      "Health check (Hepatitis B, HIV, TB)",
      "Proof of funds",
      "Academic documents",
    ],
    rejections: [
      "Missing JW form",
      "Health test failure",
      "Weak funding evidence",
    ],
    embassyUrl: "http://www.fmprc.gov.cn",
    appointmentUrl: "https://bio.visaforchina.org",
    notes:
      "CSC (Chinese Scholarship Council) deadline is typically March. X1 visa for courses > 6 months.",
  },
  KR: {
    country: "South Korea",
    processingDays: "2-4 weeks (D-2 student visa)",
    fee: "KRW 90,000 single / KRW 150,000 multiple",
    documents: [
      "Passport",
      "Certificate of Admission",
      "Proof of USD 10,000+ funds",
      "Health certificate",
      "Academic documents (apostilled)",
      "TOPIK / IELTS (depending on program)",
    ],
    rejections: [
      "Inadequate funds",
      "Unclear academic background",
      "Illegal stay history",
    ],
    embassyUrl: "https://overseas.mofa.go.kr/bd-en",
    appointmentUrl: "https://www.hikorea.go.kr",
    notes:
      "D-2 visa allows up to 25 hours/week part-time work after 6 months. TOPIK Level 3 is often required for Korean-medium programs.",
  },
  VN: {
    country: "Vietnam",
    processingDays: "1-3 weeks (DH student visa)",
    fee: "USD 25-50",
    documents: [
      "Passport",
      "Admission letter",
      "Visa invitation letter from institution",
      "Health check",
      "Academic documents",
    ],
    rejections: [
      "Missing invitation letter",
      "Unclear study plan",
    ],
    embassyUrl: "https://evisa.xuatnhapcanh.gov.vn",
    appointmentUrl: "https://evisa.xuatnhapcanh.gov.vn",
    notes:
      "University usually sponsors the DH visa. Very affordable destination with growing international programs.",
  },
  RU: {
    country: "Russia",
    processingDays: "2-3 weeks (after invitation)",
    fee: "USD 80-200",
    documents: [
      "Passport",
      "Official invitation letter from Russian university",
      "HIV certificate",
      "Academic documents (legalised)",
      "Proof of funds",
    ],
    rejections: [
      "Invitation letter mismatch",
      "Incomplete legalisation",
    ],
    embassyUrl: "https://bangladesh.mid.ru",
    appointmentUrl: "https://visa.kdmid.ru",
    notes:
      "The university issues the invitation via the Ministry of Education — this is the gating step (4-8 weeks before visa).",
  },
};

export function getVisaForCountry(code: string): VisaRequirement | null {
  return VISA_REQUIREMENTS[code.toUpperCase()] ?? null;
}
